### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by TechComet** [YePpHa/maia-yt#186]
Hi,

```
yarn build
yarn run v1.22.4
$ npm run build:userscript && npm run build:webextension

> project-maia@0.2.2 build:userscript /home/techcomet/maia-yt
> cross-env NODE_ENV=production webpack --mode production --config config/userscript.webpack.config.js

Hash: 7a34f5eccf7cae1a8b34
Version: webpack 4.44.1
Time: 13464ms
Built at: 08/26/2020 02:21:31
 1 asset
Entrypoint index = maia.user.js
[0] ./src/app/bootstrap.userscript.ts 460 bytes {0} [built] [failed] [2 errors]

ERROR in ./src/app/bootstrap.userscript.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/techcomet/maia-yt/src/app/bootstrap.userscript.ts.
    at makeSourceMapAndFinish (/home/techcomet/maia-yt/node_modules/ts-loader/dist/index.js:78:15)
    at successLoader (/home/techcomet/maia-yt/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/home/techcomet/maia-yt/node_modules/ts-loader/dist/index.js:22:12)

ERROR in /home/techcomet/maia-yt/src/app/bootstrap.inject.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/bootstrap.inject.ts(136,13)
      TS2352: Conversion of type 'Window & typeof globalThis' to type 'YTWindow' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

ERROR in /home/techcomet/maia-yt/src/app/bootstrap.inject.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/bootstrap.inject.ts(260,11)
      TS2352: Conversion of type 'Window & typeof globalThis' to type 'YTWindow' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Window & typeof globalThis' is missing the following properties from type 'YTWindow': yt, ytplayer, _yt_player

ERROR in /home/techcomet/maia-yt/src/app/bootstrap.userscript.ts
./src/app/bootstrap.userscript.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/bootstrap.userscript.ts(20,22)
      TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.

ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts(58,34)
      TS2339: Property 'fromElement' does not exist on type 'MouseEvent'.

ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts(60,34)
      TS2339: Property 'toElement' does not exist on type 'MouseEvent'.

ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts(73,89)
      TS2339: Property 'layerX' does not exist on type 'MouseEvent'.

ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/libs/events/BrowserEvent.ts(74,89)
      TS2339: Property 'layerY' does not exist on type 'MouseEvent'.

ERROR in /home/techcomet/maia-yt/src/app/libs/events/Listenable.ts
[tsl] ERROR in /home/techcomet/maia-yt/src/app/libs/events/Listenable.ts(2,10)
      TS2440: Import declaration conflicts with local declaration of 'Listenable'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! project-maia@0.2.2 build:userscript: `cross-env NODE_ENV=production webpack --mode production --config config/userscript.webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the project-maia@0.2.2 build:userscript script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/techcomet/.npm/_logs/2020-08-25T23_21_31_616Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by YePpHa** [comment]
I highly doubt much of it works anymore, but I fixed up the building. Just fetch the latest from the master branch and it should compile.
